blueprint:
    name: iBlinds+Zooz remote switch (zWaveJs)
    description: Controll an iBlinds v3 with a Zooz remote switch
    domain: automation
    input:
      controller:
        name: Zooz Remote Switch
        selector:
          device:
            #integration: "zwavejs"
            manufacturer: "Zooz"
            model: "ZEN34"

      devices:
        name: iBlinds v3 motors
        selector:
          target:
            device:
              integration: zwave_js
              manufacturer: "HAB Home Intelligence LLC"
              model: "iblinds V3"
            entity:
              integration: zwave_js
              device_class: window

trigger:
  - platform: event
    event_type: zwave_js_value_notification
    event_data:
      device_id: !input controller
      command_class_name: "Central Scene"

action:
  - service: zwave_js.set_value
    target: !input devices
    data:
      command_class: '38' # Multilevel Switch
      endpoint: '0'
      property: >
        {% if trigger.event.data.value == "KeyPressed" %}
          targetValue
        {% elif trigger.event.data.value == "KeyHeldDown" or trigger.event.data.value == "KeyReleased" %}
          {% if trigger.event.data.property_key == "001" %}
            Up
          {% elif trigger.event.data.property_key == "002" %}
            Down
          {% endif %}
        {% endif %}
      value: >
        {% if trigger.event.data.value == "KeyPressed" %}
          {% if trigger.event.data.property_key == "001" %}
            50
          {% elif trigger.event.data.property_key == "002" %}
            0
          {% endif %}
        {% elif trigger.event.data.value == "KeyHeldDown" %}
          1
        {% elif trigger.event.data.value == "KeyReleased" %}
          0
        {% endif %}
