blueprint:
    name: iBlinds+Zooz remote switch (zWaveJs)
    description: Controll an iBlinds v3 with a Zooz remote switch
    domain: automation
    input:
      controller:
        name: Zooz Remote Switch
        selector:
          device:
            integration: "zwavejs"
            manufacturer: "Zooz"
            model: "ZEN34"

      devices:
        name: iBlinds v3 motors
        selector:
          target:
            device:
              integration: zwavejs
              manufacturer: "HAB Home Intelligence LLC"
              model: "iblinds v3"
      on_tilt:
        name: "Tilt to set for \"on\""
        selector:
          number:
            min: 1
            max: 99
            mode: slider
